# Generated by Django 5.0.1 on 2024-01-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(db_column='unit_id', primary_key=True, serialize=False)),
                ('address', models.TextField(max_length=250)),
            ],
        ),
    ]
